### ISSUE TITLE
getting runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ggetv** [yogeshsr/kafka-protobuf-console-consumer#3]
Message topic:"foo" partition:156 offset:6669924
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4368079]

goroutine 487 [running]:
github.com/jhump/protoreflect/desc.(*MessageDescriptor).FindFieldByNumber(...)
	/Users/yogeshsr/go/pkg/mod/github.com/jhump/protoreflect@v0.0.0-20190612183958-f5500d91e645/desc/descriptor.go:504
github.com/jhump/protoreflect/dynamic.(*Message).FindFieldDescriptor(0xc00157be60, 0x200000001, 0x0)
	/Users/yogeshsr/go/pkg/mod/github.com/jhump/protoreflect@v0.0.0-20190612183958-f5500d91e645/dynamic/dynamic_message.go:302 +0x29
github.com/jhump/protoreflect/dynamic.(*Message).unmarshal(0xc00157be60, 0xc0005b3c40, 0x0, 0x4070932, 0xc0009b9c00)
	/Users/yogeshsr/go/pkg/mod/github.com/jhump/protoreflect@v0.0.0-20190612183958-f5500d91e645/dynamic/binary.go:420 +0x79
github.com/jhump/protoreflect/dynamic.(*Message).UnmarshalMerge(0xc00157be60, 0xc0018ce022, 0x235, 0x248, 0x1, 0xc00157be60)
	/Users/yogeshsr/go/pkg/mod/github.com/jhump/protoreflect@v0.0.0-20190612183958-f5500d91e645/dynamic/binary.go:403 +0x78
github.com/jhump/protoreflect/dynamic.(*Message).Unmarshal(0xc00157be60, 0xc0018ce022, 0x235, 0x248, 0x4a99800, 0x40c27e1)
	/Users/yogeshsr/go/pkg/mod/github.com/jhump/protoreflect@v0.0.0-20190612183958-f5500d91e645/dynamic/binary.go:392 +0x5b
github.com/yogeshsr/kafka-protobuf-console-consumer/protobuf_decoder.(*ProtobufJSONStringify).JsonString(0xc0003ffdc0, 0xc0018ce022, 0x235, 0x248, 0xc0005b3e00, 0x3, 0x3, 0x3d, 0x0)
	/Users/yogeshsr/go/src/github.com/yogeshsr/kafka-protobuf-console-consumer/protobuf_decoder/protobuf_json_stringify.go:68 +0x20d
github.com/yogeshsr/kafka-protobuf-console-consumer/consumer.SimpleConsumerGroupHandler.ConsumeClaim(0xc0003ffdc0, 0xc000000000, 0x46dbb20, 0xc00041eb00, 0x46d8fe0, 0xc00108c5a0, 0xc000680f00, 0x42b06ae)
	/Users/yogeshsr/go/src/github.com/yogeshsr/kafka-protobuf-console-consumer/consumer/protobuf_json_consumer.go:25 +0x218
github.com/Shopify/sarama.(*consumerGroupSession).consume(0xc00041eb00, 0xc0002220a0, 0xf, 0x9c)
	/Users/yogeshsr/go/pkg/mod/github.com/!shopify/sarama@v1.22.1/consumer_group.go:615 +0x27f
github.com/Shopify/sarama.newConsumerGroupSession.func2(0xc00041eb00, 0xc0002220a0, 0xf, 0xc00000009c)
	/Users/yogeshsr/go/pkg/mod/github.com/!shopify/sarama@v1.22.1/consumer_group.go:544 +0x95
created by github.com/Shopify/sarama.newConsumerGroupSession
	/Users/yogeshsr/go/pkg/mod/github.com/!shopify/sarama@v1.22.1/consumer_group.go:536 +0x526

**Comment by ggetv** [comment]
sorry for the false alarm, I set the wrong `message` parameter, instead of proto package, I am using the compiled language package.

**Comment by Khushbukela** [comment]
@ggetv @yogeshsr How this issue can be resolved?

**Comment by yogeshsr** [comment]
> @ggetv @yogeshsr How this issue can be resolved?

@Khushbukela Please add the full command here
